on:
  push:
    branches:
      - main

jobs:
  deploy_google:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      IMAGE_NAME: us-central1-docker.pkg.dev/whoami-379611/whoami

    steps:
      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Authenticate Google User
        uses: google-github-actions/auth@v1
        with:
          service_account: gc-run-service@whoami-379611.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Google Cloud Run Deployment
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: whoami-379611
          service: whoami-service
          image: gcr.io/whoami/whoami-node:latest


#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    steps:
#      # Checkout the code
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      # Authenticate with Google Cloud using the service account key
#      - name: Authenticate with Google Cloud
#        uses: ohall/whoami@main
#        with:
#          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
#          project_id: whoami
#
#      # Deploy the app to Cloud Run
#      - name: Deploy to Cloud Run
#        uses: ohall/whoami@main
#        with:
#          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
#          project_id: whoami
#          region: northamerica-northeast1
#          image: gcr.io/whoami/whoami-node:latest
#          service: whoami-service