on:
  push:
    branches:
      - main

jobs:
  google_cloud_run_build_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      LOCATION: us-central1
      PROJECT_ID: whoami-379611
      REPO: whoami
      IMAGE: whoami-node
      IMAGE_NAME: us-central1-docker.pkg.dev/whoami-379611/whoami/whoami-node

    steps:
      - name: Authenticate Google User
        uses: google-github-actions/auth@v1
        with:
          service_account: gc-run-service@whoami-379611.iam.gserviceaccount.com
          credentials_json: ${{ secrets.GCLOUD_SA_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Docker Auth
        run: docker login -u _json_key -p ${{ secrets.GCLOUD_SA_KEY }} https://${LOCATION}-docker.pkg.dev

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - name: Google Cloud Run Deployment
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          project_id: whoami-379611
          service: whoami-service
          image: $IMAGE_NAME:latest
