on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Authenticate with Google Cloud using the service account key
      - name: Authenticate with Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@main
        with:
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: whoami

      # Deploy the app to Cloud Run
      - name: Deploy to Cloud Run
        uses: GoogleCloudPlatform/github-actions/cloud-run@main
        with:
          service_account_key: ${{ secrets.GCLOUD_SA_KEY }}
          project_id: whoami
          region: northamerica-northeast1
          image: gcr.io/whoami/<IMAGE_NAME>:latest
          service: whoami-service